spring.application.name=account-service
server.port=8000

# H2
spring.datasource.url=jdbc:h2:mem:accountdb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
